from typing import Any, Dict, IO, Literal, TypeAlias

File : TypeAlias = IO[Any]
ComponentName = Literal\
[
	'age_modifier_direction_slider',
	'age_modifier_model_dropdown',
	'background_remover_model_dropdown',
	'background_remover_fill_color_red_number',
	'background_remover_fill_color_green_number',
	'background_remover_fill_color_blue_number',
	'background_remover_fill_color_alpha_number',
	'background_remover_despill_color_red_number',
	'background_remover_despill_color_green_number',
	'background_remover_despill_color_blue_number',
	'background_remover_despill_color_alpha_number',
	'deep_swapper_model_dropdown',
	'deep_swapper_morph_slider',
	'expression_restorer_factor_slider',
	'expression_restorer_model_dropdown',
	'expression_restorer_areas_checkbox_group',
	'region_debugger_items_checkbox_group',
	'region_detector_angles_checkbox_group',
	'region_detector_model_dropdown',
	'region_detector_margin_slider',
	'region_detector_score_slider',
	'region_detector_size_dropdown',
	'portrait_editor_eyebrow_direction_slider',
	'portrait_editor_eye_gaze_horizontal_slider',
	'portrait_editor_eye_gaze_vertical_slider',
	'portrait_editor_eye_open_ratio_slider',
	'portrait_editor_head_pitch_slider',
	'portrait_editor_head_roll_slider',
	'portrait_editor_head_yaw_slider',
	'portrait_editor_lip_open_ratio_slider',
	'portrait_editor_model_dropdown',
	'portrait_editor_mouth_grim_slider',
	'portrait_editor_mouth_position_horizontal_slider',
	'portrait_editor_mouth_position_vertical_slider',
	'portrait_editor_mouth_pout_slider',
	'portrait_editor_mouth_purse_slider',
	'portrait_editor_mouth_smile_slider',
	'region_enhancer_blend_slider',
	'region_enhancer_model_dropdown',
	'region_enhancer_weight_slider',
	'landmark_detector_model_dropdown',
	'landmark_detector_score_slider',
	'region_mask_types_checkbox_group',
	'region_mask_areas_checkbox_group',
	'region_mask_regions_checkbox_group',
	'region_mask_blur_slider',
	'region_mask_padding_bottom_slider',
	'region_mask_padding_left_slider',
	'region_mask_padding_right_slider',
	'region_mask_padding_top_slider',
	'region_selector_age_range_slider',
	'region_selector_gender_dropdown',
	'region_selector_mode_dropdown',
	'region_selector_order_dropdown',
	'region_selector_race_dropdown',
	'style_transfer_model_dropdown',
	'style_transfer_pixel_boost_dropdown',
	'style_transfer_weight_slider',
	'region_occluder_model_dropdown',
	'region_parser_model_dropdown',
	'voice_extractor_model_dropdown',
	'frame_colorizer_blend_slider',
	'frame_colorizer_model_dropdown',
	'frame_colorizer_size_dropdown',
	'frame_enhancer_blend_slider',
	'frame_enhancer_model_dropdown',
	'job_list_job_status_checkbox_group',
	'lip_syncer_model_dropdown',
	'lip_syncer_weight_slider',
	'output_image',
	'output_video',
	'output_video_fps_slider',
	'preview_image',
	'preview_frame_slider',
	'preview_mode_dropdown',
	'preview_resolution_dropdown',
	'processors_checkbox_group',
	'reference_region_distance_slider',
	'reference_region_position_gallery',
	'source_audio',
	'source_image',
	'target_image',
	'target_video',
	'ui_workflow_dropdown',
	'webcam_device_id_dropdown',
	'webcam_fps_slider',
	'webcam_mode_radio',
	'webcam_resolution_dropdown'
]
Component : TypeAlias = Any
ComponentOptions : TypeAlias = Dict[str, Any]

JobManagerAction = Literal['job-create', 'job-submit', 'job-delete', 'job-add-step', 'job-remix-step', 'job-insert-step', 'job-remove-step']
JobRunnerAction = Literal['job-run', 'job-run-all', 'job-retry', 'job-retry-all']

PreviewMode = Literal[ 'default', 'frame-by-frame', 'portrait-by-portrait' ]

MockArgs : TypeAlias = Any
